version: 2

sources:
  - name: retail_raw
    database: iceberg
    schema: retail_raw
    tables:
      - name: customers
      - name: products
      - name: orders
      - name: order_items
      - name: events
      - name: payments
      - name: shipments
      - name: support_tickets
